### ISSUE TITLE
Configure/control the communication of results and errors to the submitter

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#11]
When SHARE_RESULTS_IMMEDIATELY is set to false, what is the best way to share results?

Should I have a workflow step that emails participants when:

1) Prediction file is an incorrect format
2) Their scores

**Comment by brucehoff** [comment]
Yes, you can send them an email or add an explanatory annotation that appears in the submission dashboard.

**Comment by thomasyu888** [comment]
Thanks for the clarification. In my case, I think I have to create workflow steps that emails participants about their submission being invalid or scored.

This is because I want all issues with the scoring or validation function to go to me. The good thing about this is that I will have the logs of all the submissions synapse already. 

I do not want participants to have to sift through the logs to retrieve their validation errors. It's true that I can forcefully break out of the workflow if there is an issue with their prediction file but that also returns any issues with the workflow itself to them right?

What do you think?

**Comment by brucehoff** [comment]
> that also returns any issues with the workflow itself to them right?

Yes, that's a good point.  In its current form the 'hook will send an email to the submitter if you raise an exception in your workflow and the email will tell them the workflow failed.

> What do you think?

Would it help to have an option not to send any emails to the submitter?  Or to send the emails but to to the admin rather than the submitter?  Then you could have total control of the submitter's user experience (sending the emails that you prefer under the conditions that you choose).

This discussion clarifies what the issue is really about.  I took the liberty of editing the title accordingly.

**Comment by thomasyu888** [comment]
Thanks for editing the title.

> Would it help to have an option not to send any emails to the submitter? Or to send the emails but to to the admin rather than the submitter? Then you could have total control of the submitter's user experience (sending the emails that you prefer under the conditions that you choose).

I think it would be helpful to send emails to the admin rather to the submitter in the case that only prediction files are submitted, however we still want to send users their log files for their docker run.  So now we run into an issue when people submit docker containers:

1. Validate Docker -> Email step if their docker doesn't exist
2. Run Docker -> The workflowHook emails them if their docker run fails with logs
3. Validate prediction file -> Email step if their prediction file format is incorrect
4. Score prediction file -> Email step about prediction file after its scored.

How would we get around this issue?  The point of the runDocker step is for the workflow to naturally fail.

**Comment by brucehoff** [comment]
> How would we get around this issue?

Not sure what issue you are referring to.  

Maybe it helps to step back and ask, 'why does the workflow hook send emails at all?'  The answer is,
- The workflow hook is the only part of the pipeline that can monitor for failure of the entire system (i.e., it can see if the pipeline itself, not just the worflow being run, crashes).
- The workflow hook runs *in parallel* to any workflow.  So it can collect and upload partial logs, allowing the user to see the progress of something that runs for hours, days, or longer.

So it's reasonable to make the workflow hook (1) only send email for its own failures (and only send them to the submission queue administrator) and (2) not to upload logs for short running jobs.  With this curtail of responsibility for the workflow hook, it is now up to the workflow itself to perform various notification steps.  So the workflow could send all four of the notifications listed above.

Why delegate notification to the workflow?  The main answer is because notification is not generic.  Each submission queue might have its own notification needs.  A reusable .cwl notification step can be used in any workflow.

The main shortcoming of .cwl is that there is no branching logic.  You can't say, "run Step A and then, based on its output, run step B or step C."  The only way to incorporate a decision point is to raise an exception and stop the workflow altogether.  This may be enough for your purposes.    If any of step 1, 2, or 3 fail, just raise an exception and the workflow will stop.

**Comment by thomasyu888** [comment]
I agree with the shortcoming of .cwl.

I'm referring to the issue that:
1. I want to be able to notify participants if the workflow they sent fails
2. But enabling step 1, will also notify participants if the prediction scoring code fails and I do not want that.

Due to the fact that the workflowHook only look at a RECEIVED state, you recommended to write a workflow that contains the running of the docker container with the validation/scoring of the prediction file.  I could resolve the notification problem I face above by splitting up the workflow.  

1. Look for RECEIVED submissions -> Workflow that runs docker -> Returns logs (email participants)  
2. Look for OPEN/ACCEPTED submissions -> Workflow that validates and scores docker -> CWL step that emails participants about validation errors -> If the pipeline fails, email admin, or no email at all. 

Unsure if this clears things up or if I'm misunderstanding what you're saying.

**Comment by brucehoff** [comment]
> But enabling step 1, will also notify participants if the prediction scoring code fails

Not at all.  If you take control of notification in your workflow you can choose to notify them if their docker container fails (create a run-docker-and-notify-upon-failure tool) but not to notify them if the scoring fails (create a run-scoring-and-notify-upon-success tool).

>  I could resolve the notification problem I face above by splitting up the workflow.

[and letting the 'hook perform notification].  My concern is that if you split up the workflow you have begun creating your own, bespoke workflow engine.  If you can do it all in a single workflow you let the .cwl executor take care of all the things you would start having to manage (retries, concurrency, dependencies, distribution across a cluster, etc.)

> Unsure if this clears things up or if I'm misunderstanding what you're saying.

I'm saying that you can take control of notification within your workflow and tailor it to your needs.

The change I would make to the workflow hook is to add an option not to send any notifications.

**Comment by brucehoff** [comment]
@thomasyu888 explained the issue:  If a workflow is running a long running container as a sub-step, how should it do things like: monitor container state, upload logs, enforce time limit etc,  One could end up reimplementing a lot of the container management machinery of the workflow hook within a cwl tool.

We discussed several approaches but the most straight forward is to use two submission queues:
(1) Performs input validation, running the container, and output validation (steps 1, 2, 3 here https://github.com/Sage-Bionetworks/SynapseWorkflowHook/issues/11#issuecomment-426735458) It would also create a submission in another queue, submitting either (a) the submission ID of the first submission or (b) the container output file;
(2) Score the container output (step 4 here https://github.com/Sage-Bionetworks/SynapseWorkflowHook/issues/11#issuecomment-426735458)

Notifications for (1) would go to the challenge participant while notifications for (2) would go to the challenge administrator, who is the submitter for the second submission queue.  The 'hook would monitor the workflow running in (1), uploading logs periodically, enforcing time limits, etc.

**Comment by thomasyu888** [comment]
Linked from my challenge templates.  This issue can be closed.
