### ISSUE TITLE
Updating submission status breaks the hook

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#6]
When you provide a workflow that updates the submission status, it will come up with this error in the synapse workflow hook:

` WARNING: Encountered exception on attempt 7: Submission Status: 9681440 was updated since you last fetched it, retrieve it again and reapply the update`

A solution is to download the status prior to trying to update it again

**Comment by brucehoff** [comment]
This happens because both the 'workflow hook' and the workflow are annotating the same submission at the same time.  Solution is to add exponential backoff/retry of the process of downloading the status, applying changes, and pushing the changes back to Synapse.    This should be done both (1) in the 'hook, and (2) in the CWL script for annotating a submission (https://github.com/Sage-Bionetworks/SynapseWorkflowExample/blob/master/annotateSubmission.cwl)

**Comment by brucehoff** [comment]
Here's the change to add exponential backoff/retry to the workflow:
https://github.com/Sage-Bionetworks/SynapseWorkflowExample/commit/7e3242c3ac1d09d2cba150bb3c2ddcb697f7e638
and here's the change to add it to the WorkflowHook:
https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/8a8c1c2563765dd293ccc83f658059838b0b99f5
